CREATE TABLE IF NOT EXISTS mahasiswa(
	id VARCHAR(255) NOT NULL,
	nim VARCHAR(255) NOT NULL,
	nama VARCHAR(255) NOT NULL,
    jurusan VARCHAR(255) NOT NULL,
    ipk FLOAT(4,2) NOT NULL,
    PRIMARY KEY(id)
)ENGINE=InnoDB;